# Generated by Django 4.2.7 on 2023-11-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(blank=True, max_length=2)),
                ('summer_level', models.CharField(blank=True, max_length=2)),
                ('autumn_level', models.CharField(blank=True, max_length=2)),
                ('spring_level', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'pereval_level',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pereval_user',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('NW', 'Новое'), ('PD', 'В процессе'), ('AC', 'Информация принята'), ('RJ', 'Информация не принята')], default='NW', max_length=2)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coords')),
                ('levels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'pereval_add',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.pereval')),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
    ]
